Host state root
dusk-network/canonical pull request #53
Opened 2020-12-08 16:09 UTC by krl

2020-12-09 21:39 UTC, krl commented
@ZER0 sorry for removing your test for now, we need to discuss how to deal with this since i'm not sure if i understand exactly what you're trying to do with the externals.

2020-12-14 09:35 UTC, CPerezz requested changes
Hey. I like a lot the solution overall, just have some questions that left in the code.

I only have one problem which is the fact that this PR appart from implementing inter-contract calls is removing the work done in #56  and #49 .

Could you rebase to master in order to avoid this removal?

2020-12-14 09:35 UTC, CPerezz commented on canon_host/tests/root_test.rs
> +}
I'm unsure how this is going to work once we integrate it. 

Does this mean that we will need to append to this structure all of the contracts? Is this a structure just created to generate delagate calls?

2020-12-22 12:46 UTC, CPerezz commented
Considering that this is going to be moved to `rusk_vm` I would either set it as draft so that the code is still reachable or if you have it on some other place, just close the PR and remove the branch.

Any suggestions @krl ?

2020-12-23 12:06 UTC, closed without merging