use const generics instead of a macro for arrays
dusk-network/canonical pull request #91
Opened 2021-04-20 11:59 UTC by m-marcello

2021-04-20 12:16 UTC, krl approved these changes
Looks great!

2021-04-20 16:25 UTC, ZER0 requested changes
Looks great! I would just address the comments below to use iterators instead of loops.

Also, the commit message should be rephrase as following (or similar):
```
canonical: Replace macro for arrays with const generics

Resolves: #77
```

As discussed, the commit message is following mostly [these guidelines](https://chris.beams.io/posts/git-commit/).
In addition, the prefix `canonical:` is needed since canonical is a workspace repo, so we need to ensure each commit is atomic to one crate (like in your case) and the crate's name is added as prefix to the commit's message (since all member of the workspace shares the same github history).

Said that, since we're merging with master and this is a minor change, we should also update in the same patch the canonical's version (from `0.6.0` to `0.6.1`) and update the CHANGELOG.

This changes should be separate commits, so eventually you should have 3 commits:

1. The commit that contains the code currently in this PR
2. The changelog update
3. The bump to 0.6.1

If you prefer you can have one commit ("Bump to 0.6.1") that also includes the changelog changes, it's up to you.

2021-04-22 11:10 UTC, m-marcello commented
I have added the changes in the changelog under 'Unreleased'. I will move them into the version 0.6.1 when merging with master.

2021-05-03 12:54 UTC, ZER0 approved these changes

2021-05-03 12:55 UTC, merged